### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3

### ISSUE THREAD

**Issue by Emanulator** [Turnip-Labs/bta-example-mod-archive#1]
Since the example dimension got added (commit 20c8bf2194b240bd17e3579324908dca5a0fc1e5) mod crashes server when creating/loading a world

<details>
<summary>Details</summary>

> 2022-10-20 08:43:29 [INFO] Starting minecraft server version Beta 1.7.6.2_02
2022-10-20 08:43:29 [INFO] Loading properties
2022-10-20 08:43:29 [INFO] Starting Minecraft server on *:25565
2022-10-20 08:43:29 [SEVERE] Unexpected exception
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
	at net.minecraft.server.MinecraftServer.startServer(MinecraftServer.java:132)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:271)
	at net.minecraft.src.ThreadServerApplication.run(ThreadServerApplication.java:20)

</details>

Steps to reproduce:

1) Install Babric Server with https://babric.github.io/use/installer
2) replace server.jar with the one from BTA
3) compile examplemod jar from this repo
4) create mods folder in server folder and copy compiled mod jar to it
5) start server using start.bat
6) see log

![consolewindow](https://user-images.githubusercontent.com/14092505/196876193-b2cc9afb-3739-41cf-8f48-24d7b1cf1691.png)

**Comment by azuredao8** [comment]
Fixed with [2cbc243](https://github.com/azurelmao/bta-babric-example-mod/commit/2cbc2432e56785c5a816dfc807fbfe11af4fc7a5)
